apiVersion: v1
kind: ConfigMap
metadata:
  name: usersapi-config
  namespace: fiap-cloud-games
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_HOST: rabbitmq
  DATABASE_HOST: mysql-users
  DATABASE_NAME: "usersdb"
  CatalogAPI_Url: http://catalogapi:80
  PaymentsAPI_Url: http://payments:80
  NotificationAPI_Url: http://notification:80
