apiVersion: v1
kind: ConfigMap
metadata:
  name: usersapi-config
  namespace: fiap-cloud-games
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_HOST: rabbitmq
  DATABASE_HOST: mysql-users
  DATABASE_NAME: "usersdb"