apiVersion: v1
kind: Secret
metadata:
  name: usersapi-secret
  namespace: fiap-cloud-games
type: Opaque
stringData:
  ConnectionStrings__Users: "Server=mysql-service;Database=users_db;User=fiapDbUser!;Password=!H2rOs21aa;"
  Jwt__Key: "]bvw*4YTYfi#15edCO38hfrR{hKUFJYdIdsuYNvBEGdXfgjAiKsdl"
#Server=mysql-service;
#Database=users_db;
#User=fiapDbUser!;
#Password=!H2rOs21aa;